module ApplicationHelper

  def course_subjects
    %w{ AAAS AMEL AMES ANTH ARAB ARTH ASTR BIOL CHEM CHIN CLST COCO COGS COLT COSC 
      EARS ECON EDUC ENGL ENGS ENVS FILM FREN FRIT FYS GEOG GERM GOVT GRK HEBR HIST
      HUM INTS ITAL HAPN JWST LACS LAT LATS LING M&SS MATH MUS NAS PBPL PHIL PHYS 
      PORT PSYC REL RUSS SART SOCY SPAN SPEE SSOC THEA TUCK WGST WPS WRIT }
  end
end
